name = "First"
uuid = "873cae1f-969f-456b-9f29-54d7ddcb659b"
authors = ["Vinish M"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
